/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yk_text_media_MainActivity */

#ifndef _Included_com_yk_text_media_MainActivity
#define _Included_com_yk_text_media_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yk_text_media_MainActivity
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yk_text_1media_MainActivity_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_yk_text_media_MainActivity
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yk_text_1media_MainActivity_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
